channels:
  - conda-forge
  - bioconda
  - nvidia
dependencies:
  - gcc_linux-64=14.1.0
  - python=3.12
  - cuda=12.1
  # - cudatoolkit=12.1 # It possibly needs this but not in the documentation!
  - pip
  - pip:
      - chai_lab==0.3.0
